server:
  port: 9907

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      mvc:
        routes:
          - id: customer-service
            uri: lb://CUSTOMER-SERVICE
            predicates:
              - Path=/customer-service/**,/rabbitmq-producer/**

          - id: hotel-service
            uri: lb://HOTEL-SERVICE
            predicates:
              - Path=/hotel-service/**

          - id: fraud-service
            uri: lb://FRAUD-SERVICE
            predicates:
              - Path=/fraud-service/**

          - id: rating-service
            uri: lb://RATING-SERVICE
            predicates:
              - Path=/rating-service/**

          - id: ollama
            uri: lb://OLLAMA
            predicates:
              - Path=/ollama/**

          - id: notification-service
            uri: lb://NOTIFICATION-SERVICE
            predicates:
              - Path=/notification-service/**

          - id: consumer-service
            uri: lb://CONSUMER-SERVICE
            predicates:
              - Path=/consumer-service/**

# Eureka client configuration
eureka:
  instance:
    prefer-ip-address: true
    appname: api-gateway
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

# logging configurations
logging:
  level:
    com.learning.apigateway: debug
