server:
  port: 9900

spring:
  application:
    name: user-service
  data:
    mongodb:
      port: 27018
      uri: mongodb://root:secret@localhost:27018/profile-database?authSource=admin

# Eureka client configuration
eureka:
  instance:
    prefer-ip-address: true
    appname: user-service
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

# logging configurations
logging:
  level:
    com.learning.profile: debug

startup-actions:
  initializeProfiles: true

user:
  default:
    profile:
      character: "{'profileId':'8b0e4a15-95c2-45bd-937d-f111a8bfbfec', 'firstName':'Vivek', 'lastName':'Kumar', 'age':27, 'ethnicity':'Indian', 'gender':'MALE', 'bio':'Software engineer, teacher and learner. I like reading and making things.', 'imageUrl':'', 'myersBriggsPersonalityType':'INTP'}"
