server:
  port: 9903

spring:
  application:
    name: fraud-service
  datasource:
    username: 'root'
    password: 'secret'
    url: jdbc:postgresql://localhost:5433/fraud
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: 'true'
        dialect: org.hibernate.dialect.PostgreSQLDialect

# Eureka client configuration
eureka:
  instance:
    prefer-ip-address: true
    appname: fraud-service
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/


# logging configurations
logging:
  level:
    com.learning.fraudservice: debug
